### ISSUE TITLE
Guardian 'Taunt' action doesn't use class DC

### ISSUE THREAD

**Issue by SudoProgramming** [ubik2/DawnsburyDaysMod#3]
According to the tooltip 'a Will save against your class DC', but the Taunt action uses your characters Intelligence modifier instead of the class DC modifier instead of Strength.

The character below in the image has a +4 in strength and +0 intelligence, and if I make a +3 intelligence Guardian the Taunt goes up it DC 17.
![image](https://github.com/user-attachments/assets/8f7830b4-5f03-4d74-9fb8-690e1a7ab4d5)

The following line appears to be cause:
https://github.com/ubik2/DawnsburyDaysMod/blob/c883ce97640dfe726b7a159546409dc451b850ae/Dawnsbury.Mods.Battlecry/Guardian.cs#L336

**Comment by ubik2** [comment]
Thanks for the bug report (as well as tracing down the source). This should be fixed now.

**Comment by ubik2** [comment]
deployed correction to steam
